### ISSUE TITLE
Meta-data Content

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Neuroscience#10]
each page needs:

meta-description: 100 to 160 or characters unique to this page
meta-keywords: 3 or 4 unique for this page

**Comment by tu-chill** [comment]
Meta descriptions can be any length, but search engines truncate snippets longer than 160 characters. It is best to keep meta descriptions long enough that they're sufficiently descriptive but shorter than that 160-character limit.

Meta Keywords are a particular type of meta tag that appears in the HTML code of a Web page and helps tell search engines what the topic of the page is.

**Comment by saracurnow** [comment]
Took a shot at adding meta descriptions to each neuro page. Not sure if I'm doing them right (should they actually be sentences?), take a look at them when you get a chance and let me know what you think. Thanks!

**Comment by tu-chill** [comment]
done
