### ISSUE TITLE
Content removed from Resources Page

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Neuroscience#11]
The following items are intranet and do not belong on the resources page catered to prospective students. Suggestions can be made to the program as to where this should be housed outside of the website.

[MisplacedNeuroscienceResources.docx](https://github.com/TULiberalArts/Neuroscience/files/1075740/MisplacedNeuroscienceResources.docx)

**Comment by tu-chill** [comment]
Looking at the content on resources page at the time of launch - I believe we can move the information to the undergraduate page and remove the resources page altogether.

**Comment by tu-chill** [comment]
Both Student resources have content on the internet. Are we duplicating content? Can we say less and provide a link to these Temple pages? or do these pages have their own Sites.temple.edu set up?

https://temple.campuslabs.com/engage/organization/nurhopsi
https://temple.campuslabs.com/engage/organization/Undergraduate_Neuroscience_Society

**Comment by CVE82** [comment]
I am re-adding the links now =) We can look at trimming that content since it's already out there...

**Comment by CVE82** [comment]
The resources have been distributed within the content throughout the site.
