### ISSUE TITLE
Missing Next Stops content

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Neuroscience#12]
Hey so I know we are customizing the Last Stops pages but we are still keeping the fact sheet info too. (screenshot below) All of the other sites have their next stops listed and then the fact sheet info. The undergraduate page doesn't have options to visit or apply; without the deadlines, visit and apply links undergraduate students cannot easily access this information. 
![image](https://user-images.githubusercontent.com/15130721/27448240-1004d36c-5752-11e7-81a6-d37a93820380.png)

Was this removal of content a request from Debra or Parikh? Thanks!

**Comment by saracurnow** [comment]
If I remember correctly, the removal was not a request from the department. We did it before we sent the dev site out for approval because we thought there was already too much content on that page. I'll add it back right now.
