### ISSUE TITLE
4+1 Content

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Neuroscience#3]
Please do not edit or remove any of the new 4+1 content. These are brand new revisions written by the director Vinay and the program is not on the bulletin yet to link to so the description, deadlines and application instructions need to be stated as they are.

**Comment by saracurnow** [comment]
FYI: I did make one small change to the 4+1 Neuroscience content. After noticing that it said BA in one place and BS in another, I asked Debbie Bangasser (the other program director) which it should be. She said it's a BS so I updated the content to reflect this. Let me know if you have any questions!

**Comment by CVE82** [comment]
Yes it's a BS, thank you.
