### ISSUE TITLE
Missing form on neuro research page

### ISSUE THREAD

**Issue by saracurnow** [TULiberalArts/Neuroscience#6]
The following paragraph appears under Registering for Independent Study on the neuro research page: 

"In order to register for Independent Study, you need a Special Course Approval form. These forms can be found on this website under student resources Special Course Form or they can be found at the Neuroscience Advising office in room 638 Weiss Hall."

I can't find this form anywhere. Any ideas (besides deleting the part about finding it online)?

**Comment by CVE82** [comment]
Hey Sarah! So they never had a form for this in doc or pdf, uploaded to the old site under student resources. I would just remove the "available online" text. Thanks!

**Comment by saracurnow** [comment]
Great, thanks!

**Comment by CVE82** [comment]
You are more than welcome!
