### ISSUE TITLE
Anthropology faculty on neuroscience page

### ISSUE THREAD

**Issue by saracurnow** [TULiberalArts/Neuroscience#7]
Zach may have already mentioned this to someone, but the faculty showing up on the neuroscience page right now are from the anthropology department.

**Comment by CVE82** [comment]
Hey Sarah! Nothing was mentioned but I am checking files now to see where the error lies =) Thanks for bring this to my attention!

**Comment by CVE82** [comment]
All fixed! Neuro faculty is up! Thanks again!

**Comment by saracurnow** [comment]
Great, thanks!
