### ISSUE TITLE
Quick neuroscience faculty question

### ISSUE THREAD

**Issue by saracurnow** [TULiberalArts/Neuroscience#8]
Good morning!

There are three neuro faculty members we have profiles for but do not appear on the website (their "faculty" box isn't checked in Drupal). It looks like they're all College of Public Health faculty members. Have they been intentionally left off our page for this reason, or should I add them back to the neuro page?

**Comment by saracurnow** [comment]
The faculty members are Carole Tucker, Emily Keshner & Richard Lauer

**Comment by CVE82** [comment]
Hey Sarah, they are affiliated faculty and the box should've been checked, Drupal does that sometimes. Yes please add them back in, you can see them at www.cla.temple.edu/neuroscience/ 
=D

**Comment by saracurnow** [comment]
Great, just wanted to make sure. Thanks!

**Comment by saracurnow** [comment]
One more thing Camille--there are faculty members on the existing neuro page (http://www.cla.temple.edu/neuroscience/faculty-2/) that I can't find in Drupal anywhere. Lynn Kirby and Dianne Langford are two examples. Do you know if I should be manually migrating those profiles over?

**Comment by CVE82** [comment]
Thanks Sarah I'm on my way in now so I will take a look when I get in.

**Comment by CVE82** [comment]
Hey Sarah! All faculty is in, Chris and I are just working on some back end configuration to get John Mushcamp in the proper alphabetical order. Thanks!

**Comment by saracurnow** [comment]
Great, thanks!
