### ISSUE TITLE
Homepage image gradient

### ISSUE THREAD

**Issue by zepstein** [TULiberalArts/Neuroscience#9]
Hey -- can we add a gradient or some shading over the homepage image, so it's slightly easier to read the white text?

**Comment by CVE82** [comment]
Victor we were going to leave it blue but add gradient. Please do not shade red.

**Comment by tu-chill** [comment]
@ZMcGroarty I think this is resolved. Can we close it?

**Comment by ZMcGroarty** [comment]
Yep
